[workspace]
resolver = "2"
members = ["client", "server", "sidecar"]

[workspace.dependencies]
bevy = { version = "0.16.1" }
bevy_spacetimedb = { version = "1.0.0" }
spacetimedb-sdk = { version = "1.3.0" }
