// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.3.0 (commit cc4a165627f041ba50c7554361a549373876a90d).

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct AuthServerResponseArgs {
    pub(crate) steam_id: u64,
    pub(crate) identity: __sdk::Identity,
    pub(crate) err_msg: String,
}

impl From<AuthServerResponseArgs> for super::Reducer {
    fn from(args: AuthServerResponseArgs) -> Self {
        Self::AuthServerResponse {
            steam_id: args.steam_id,
            identity: args.identity,
            err_msg: args.err_msg,
        }
    }
}

impl __sdk::InModule for AuthServerResponseArgs {
    type Module = super::RemoteModule;
}

pub(crate) struct AuthServerResponseCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `auth_server_response`.
///
/// Implemented for [`super::RemoteReducers`].
pub(crate) trait auth_server_response {
    /// Request that the remote module invoke the reducer `auth_server_response` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_auth_server_response`] callbacks.
    fn auth_server_response(
        &self,
        steam_id: u64,
        identity: __sdk::Identity,
        err_msg: String,
    ) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `auth_server_response`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`AuthServerResponseCallbackId`] can be passed to [`Self::remove_on_auth_server_response`]
    /// to cancel the callback.
    fn on_auth_server_response(
        &self,
        callback: impl FnMut(&super::ReducerEventContext, &u64, &__sdk::Identity, &String)
            + Send
            + 'static,
    ) -> AuthServerResponseCallbackId;
    /// Cancel a callback previously registered by [`Self::on_auth_server_response`],
    /// causing it not to run in the future.
    fn remove_on_auth_server_response(&self, callback: AuthServerResponseCallbackId);
}

impl auth_server_response for super::RemoteReducers {
    fn auth_server_response(
        &self,
        steam_id: u64,
        identity: __sdk::Identity,
        err_msg: String,
    ) -> __sdk::Result<()> {
        self.imp.call_reducer(
            "auth_server_response",
            AuthServerResponseArgs {
                steam_id,
                identity,
                err_msg,
            },
        )
    }
    fn on_auth_server_response(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &u64, &__sdk::Identity, &String)
            + Send
            + 'static,
    ) -> AuthServerResponseCallbackId {
        AuthServerResponseCallbackId(self.imp.on_reducer(
            "auth_server_response",
            Box::new(move |ctx: &super::ReducerEventContext| {
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer:
                                super::Reducer::AuthServerResponse {
                                    steam_id,
                                    identity,
                                    err_msg,
                                },
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx, steam_id, identity, err_msg)
            }),
        ))
    }
    fn remove_on_auth_server_response(&self, callback: AuthServerResponseCallbackId) {
        self.imp
            .remove_on_reducer("auth_server_response", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `auth_server_response`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub(crate) trait set_flags_for_auth_server_response {
    /// Set the call-reducer flags for the reducer `auth_server_response` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn auth_server_response(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_auth_server_response for super::SetReducerFlags {
    fn auth_server_response(&self, flags: __ws::CallReducerFlags) {
        self.imp
            .set_call_reducer_flags("auth_server_response", flags);
    }
}
