// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.3.0 (commit cc4a165627f041ba50c7554361a549373876a90d).

#![allow(unused, clippy::all)]
use super::auth_request_type::AuthRequest;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `auth_request`.
///
/// Obtain a handle from the [`AuthRequestTableAccess::auth_request`] method on [`super::RemoteTables`],
/// like `ctx.db.auth_request()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.auth_request().on_insert(...)`.
pub(crate) struct AuthRequestTableHandle<'ctx> {
    imp: __sdk::TableHandle<AuthRequest>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `auth_request`.
///
/// Implemented for [`super::RemoteTables`].
pub(crate) trait AuthRequestTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`AuthRequestTableHandle`], which mediates access to the table `auth_request`.
    fn auth_request(&self) -> AuthRequestTableHandle<'_>;
}

impl AuthRequestTableAccess for super::RemoteTables {
    fn auth_request(&self) -> AuthRequestTableHandle<'_> {
        AuthRequestTableHandle {
            imp: self.imp.get_table::<AuthRequest>("auth_request"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub(crate) struct AuthRequestInsertCallbackId(__sdk::CallbackId);
pub(crate) struct AuthRequestDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for AuthRequestTableHandle<'ctx> {
    type Row = AuthRequest;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = AuthRequest> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = AuthRequestInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> AuthRequestInsertCallbackId {
        AuthRequestInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: AuthRequestInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = AuthRequestDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> AuthRequestDeleteCallbackId {
        AuthRequestDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: AuthRequestDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<AuthRequest>("auth_request");
    _table.add_unique_constraint::<u64>("steam_id", |row| &row.steam_id);
    _table.add_unique_constraint::<__sdk::Identity>("identity", |row| &row.identity);
}
pub(crate) struct AuthRequestUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for AuthRequestTableHandle<'ctx> {
    type UpdateCallbackId = AuthRequestUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> AuthRequestUpdateCallbackId {
        AuthRequestUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: AuthRequestUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<AuthRequest>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<AuthRequest>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `steam_id` unique index on the table `auth_request`,
/// which allows point queries on the field of the same name
/// via the [`AuthRequestSteamIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.auth_request().steam_id().find(...)`.
pub(crate) struct AuthRequestSteamIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<AuthRequest, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> AuthRequestTableHandle<'ctx> {
    /// Get a handle on the `steam_id` unique index on the table `auth_request`.
    pub(crate) fn steam_id(&self) -> AuthRequestSteamIdUnique<'ctx> {
        AuthRequestSteamIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("steam_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> AuthRequestSteamIdUnique<'ctx> {
    /// Find the subscribed row whose `steam_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub(crate) fn find(&self, col_val: &u64) -> Option<AuthRequest> {
        self.imp.find(col_val)
    }
}

/// Access to the `identity` unique index on the table `auth_request`,
/// which allows point queries on the field of the same name
/// via the [`AuthRequestIdentityUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.auth_request().identity().find(...)`.
pub(crate) struct AuthRequestIdentityUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<AuthRequest, __sdk::Identity>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> AuthRequestTableHandle<'ctx> {
    /// Get a handle on the `identity` unique index on the table `auth_request`.
    pub(crate) fn identity(&self) -> AuthRequestIdentityUnique<'ctx> {
        AuthRequestIdentityUnique {
            imp: self
                .imp
                .get_unique_constraint::<__sdk::Identity>("identity"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> AuthRequestIdentityUnique<'ctx> {
    /// Find the subscribed row whose `identity` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub(crate) fn find(&self, col_val: &__sdk::Identity) -> Option<AuthRequest> {
        self.imp.find(col_val)
    }
}
