// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.3.0 (commit cc4a165627f041ba50c7554361a549373876a90d).

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct BeginClientAuthArgs {
    pub(crate) steam_id: u64,
    pub(crate) ticket: Vec<u8>,
}

impl From<BeginClientAuthArgs> for super::Reducer {
    fn from(args: BeginClientAuthArgs) -> Self {
        Self::BeginClientAuth {
            steam_id: args.steam_id,
            ticket: args.ticket,
        }
    }
}

impl __sdk::InModule for BeginClientAuthArgs {
    type Module = super::RemoteModule;
}

pub(crate) struct BeginClientAuthCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `begin_client_auth`.
///
/// Implemented for [`super::RemoteReducers`].
pub(crate) trait begin_client_auth {
    /// Request that the remote module invoke the reducer `begin_client_auth` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_begin_client_auth`] callbacks.
    fn begin_client_auth(&self, steam_id: u64, ticket: Vec<u8>) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `begin_client_auth`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`BeginClientAuthCallbackId`] can be passed to [`Self::remove_on_begin_client_auth`]
    /// to cancel the callback.
    fn on_begin_client_auth(
        &self,
        callback: impl FnMut(&super::ReducerEventContext, &u64, &Vec<u8>) + Send + 'static,
    ) -> BeginClientAuthCallbackId;
    /// Cancel a callback previously registered by [`Self::on_begin_client_auth`],
    /// causing it not to run in the future.
    fn remove_on_begin_client_auth(&self, callback: BeginClientAuthCallbackId);
}

impl begin_client_auth for super::RemoteReducers {
    fn begin_client_auth(&self, steam_id: u64, ticket: Vec<u8>) -> __sdk::Result<()> {
        self.imp.call_reducer(
            "begin_client_auth",
            BeginClientAuthArgs { steam_id, ticket },
        )
    }
    fn on_begin_client_auth(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &u64, &Vec<u8>) + Send + 'static,
    ) -> BeginClientAuthCallbackId {
        BeginClientAuthCallbackId(self.imp.on_reducer(
            "begin_client_auth",
            Box::new(move |ctx: &super::ReducerEventContext| {
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer: super::Reducer::BeginClientAuth { steam_id, ticket },
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx, steam_id, ticket)
            }),
        ))
    }
    fn remove_on_begin_client_auth(&self, callback: BeginClientAuthCallbackId) {
        self.imp.remove_on_reducer("begin_client_auth", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `begin_client_auth`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub(crate) trait set_flags_for_begin_client_auth {
    /// Set the call-reducer flags for the reducer `begin_client_auth` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn begin_client_auth(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_begin_client_auth for super::SetReducerFlags {
    fn begin_client_auth(&self, flags: __ws::CallReducerFlags) {
        self.imp.set_call_reducer_flags("begin_client_auth", flags);
    }
}
