// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.3.0 (commit cc4a165627f041ba50c7554361a549373876a90d).

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct ExitQueueArgs {}

impl From<ExitQueueArgs> for super::Reducer {
    fn from(args: ExitQueueArgs) -> Self {
        Self::ExitQueue
    }
}

impl __sdk::InModule for ExitQueueArgs {
    type Module = super::RemoteModule;
}

pub(crate) struct ExitQueueCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `exit_queue`.
///
/// Implemented for [`super::RemoteReducers`].
pub(crate) trait exit_queue {
    /// Request that the remote module invoke the reducer `exit_queue` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_exit_queue`] callbacks.
    fn exit_queue(&self) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `exit_queue`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`ExitQueueCallbackId`] can be passed to [`Self::remove_on_exit_queue`]
    /// to cancel the callback.
    fn on_exit_queue(
        &self,
        callback: impl FnMut(&super::ReducerEventContext) + Send + 'static,
    ) -> ExitQueueCallbackId;
    /// Cancel a callback previously registered by [`Self::on_exit_queue`],
    /// causing it not to run in the future.
    fn remove_on_exit_queue(&self, callback: ExitQueueCallbackId);
}

impl exit_queue for super::RemoteReducers {
    fn exit_queue(&self) -> __sdk::Result<()> {
        self.imp.call_reducer("exit_queue", ExitQueueArgs {})
    }
    fn on_exit_queue(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext) + Send + 'static,
    ) -> ExitQueueCallbackId {
        ExitQueueCallbackId(self.imp.on_reducer(
            "exit_queue",
            Box::new(move |ctx: &super::ReducerEventContext| {
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer: super::Reducer::ExitQueue {},
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx)
            }),
        ))
    }
    fn remove_on_exit_queue(&self, callback: ExitQueueCallbackId) {
        self.imp.remove_on_reducer("exit_queue", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `exit_queue`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub(crate) trait set_flags_for_exit_queue {
    /// Set the call-reducer flags for the reducer `exit_queue` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn exit_queue(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_exit_queue for super::SetReducerFlags {
    fn exit_queue(&self, flags: __ws::CallReducerFlags) {
        self.imp.set_call_reducer_flags("exit_queue", flags);
    }
}
