// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.3.0 (commit cc4a165627f041ba50c7554361a549373876a90d).

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct OnClientDisconnectedArgs {}

impl From<OnClientDisconnectedArgs> for super::Reducer {
    fn from(args: OnClientDisconnectedArgs) -> Self {
        Self::OnClientDisconnected
    }
}

impl __sdk::InModule for OnClientDisconnectedArgs {
    type Module = super::RemoteModule;
}

pub(crate) struct OnClientDisconnectedCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `on_client_disconnected`.
///
/// Implemented for [`super::RemoteReducers`].
pub(crate) trait on_client_disconnected {
    /// Request that the remote module invoke the reducer `on_client_disconnected` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_on_client_disconnected`] callbacks.
    fn on_client_disconnected(&self) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `on_client_disconnected`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`OnClientDisconnectedCallbackId`] can be passed to [`Self::remove_on_on_client_disconnected`]
    /// to cancel the callback.
    fn on_on_client_disconnected(
        &self,
        callback: impl FnMut(&super::ReducerEventContext) + Send + 'static,
    ) -> OnClientDisconnectedCallbackId;
    /// Cancel a callback previously registered by [`Self::on_on_client_disconnected`],
    /// causing it not to run in the future.
    fn remove_on_on_client_disconnected(&self, callback: OnClientDisconnectedCallbackId);
}

impl on_client_disconnected for super::RemoteReducers {
    fn on_client_disconnected(&self) -> __sdk::Result<()> {
        self.imp
            .call_reducer("on_client_disconnected", OnClientDisconnectedArgs {})
    }
    fn on_on_client_disconnected(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext) + Send + 'static,
    ) -> OnClientDisconnectedCallbackId {
        OnClientDisconnectedCallbackId(self.imp.on_reducer(
            "on_client_disconnected",
            Box::new(move |ctx: &super::ReducerEventContext| {
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer: super::Reducer::OnClientDisconnected {},
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx)
            }),
        ))
    }
    fn remove_on_on_client_disconnected(&self, callback: OnClientDisconnectedCallbackId) {
        self.imp
            .remove_on_reducer("on_client_disconnected", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `on_client_disconnected`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub(crate) trait set_flags_for_on_client_disconnected {
    /// Set the call-reducer flags for the reducer `on_client_disconnected` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn on_client_disconnected(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_on_client_disconnected for super::SetReducerFlags {
    fn on_client_disconnected(&self, flags: __ws::CallReducerFlags) {
        self.imp
            .set_call_reducer_flags("on_client_disconnected", flags);
    }
}
