[package]
name = "sidecar"
version = "0.1.0"
edition = "2024"

[dependencies]
tracing = { version = "0.1.41" }
tracing-subscriber = { version = "0.3.20" }
tracing-log = { version = "0.2.0" }
steamworks = { version = "0.12.2" }
spacetimedb-sdk = { workspace = true }
