name: Cargo Clippy

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    - name: Run clippy
      run: cargo clippy -- -D warnings -D missing_docs -D unused_imports -D unused_variables -D unused_must_use -D future_incompatible
